server:
  port: 8082
spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: 192.168.29.134:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.example.processing_service.dto
        spring.json.value.default.type: com.example.processing_service.dto.NewsArticle
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
openai:
  api-key: "<OPEN_API_KEY>"