apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-service
  template:
    metadata:
      labels:
        app: processing-service
    spec:
      containers:
        - name: processing-service
          image: processing-service:1.0
          ports:
            - containerPort: 8082 # Change to your app's port